# Generated by Django 5.0 on 2025-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='quanity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
