# Generated by Django 5.0 on 2025-10-19 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_app', '0002_ingredient_quanity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
