# Generated by Django 5.0 on 2025-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredient_app', '0003_rename_quanity_ingredient_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='price',
            new_name='price_bulk',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='quantity',
            new_name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='name',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='about_the_product',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='bulk_unit',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='characteristics',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='legal_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='nutrition_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='other_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='size',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='size_type',
            field=models.CharField(choices=[('PACKAGE', 'Package'), ('BULK', 'Bulk')], default='teste', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='title',
            field=models.CharField(default='teste', max_length=255),
            preserve_default=False,
        ),
    ]
