# Generated by Django 5.0 on 2025-06-15 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_app', '0001_initial'),
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked', models.BooleanField(default=False)),
                ('quantity', models.FloatField()),
                ('extra_quantity', models.FloatField(null=True)),
                ('units', models.CharField(default='G', max_length=255)),
                ('extra_units', models.CharField(max_length=255, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_ingredients', to='recipe_app.ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('archived', models.BooleanField(default=False)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_lists', to='group_app.group')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
