# Generated by Django 5.0 on 2025-10-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shoppingingredient',
            name='units',
            field=models.CharField(default='g', max_length=255),
        ),
    ]
