# Generated by Django 5.0 on 2025-11-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_shoppingingredient_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingingredient',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
