# Generated by Django 5.0 on 2024-07-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
