# Generated by Django 5.0 on 2024-08-16 18:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_app', '0004_groupinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupinvite',
            unique_together={('inviter', 'invited')},
        ),
        migrations.RemoveField(
            model_name='groupinvite',
            name='img_source',
        ),
    ]
