# Generated by Django 5.0 on 2024-10-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='company',
        ),
        migrations.RemoveField(
            model_name='task',
            name='extract_sql_file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='transform_sql_file',
        ),
    ]
