# Generated by Django 5.0 on 2024-11-12 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_remove_task_paused_at_remove_task_resumed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='stopping_condition_max_records',
        ),
    ]
