# Generated by Django 5.0 on 2024-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0007_alter_task_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaxRecordsCondition',
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_view_task', "Can view task's details"), ('can_view_tasks', 'Can view tasks list'), ('can_create_task', 'Can create task'), ('can_edit_task', 'Can edit task'), ('can_restart_task', 'Can restart task'), ('can_stop_task', 'Can stop task'), ('can_resume_task', 'Can resume task'), ('can_cancel_task', 'Can cancel task'), ('can_delete_task', 'Can delete task')]},
        ),
        migrations.AddField(
            model_name='task',
            name='counter',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STARTING', 'Starting'), ('PAUSED', 'Paused'), ('RUNNING', 'Running'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='STARTING', max_length=10),
        ),
    ]
