# Generated by Django 5.0 on 2024-11-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0008_delete_maxrecordscondition_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='counter',
            new_name='step',
        ),
    ]
