# Generated by Django 5.0 on 2024-11-15 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0010_remove_task_celery_task_id_celeryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celeryid',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='celery_tasks', to='task_app.task'),
        ),
    ]
