# Generated by Django 5.0 on 2024-11-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0011_alter_celeryid_task_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CeleryId',
            new_name='CeleryTask',
        ),
        migrations.RenameField(
            model_name='celerytask',
            old_name='task_id',
            new_name='task',
        ),
    ]
