# Generated by Django 5.0 on 2024-11-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0014_remove_job_debug_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='last_run',
        ),
        migrations.RemoveField(
            model_name='job',
            name='parent_job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='parent_task',
        ),
    ]
