# Generated by Django 5.0 on 2024-11-20 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('task_app', '0015_remove_job_company_remove_job_last_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
