# Generated by Django 5.0 on 2024-11-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0017_job_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='enabled',
        ),
    ]
