# Generated by Django 5.0 on 2024-11-21 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0018_remove_job_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
