# Generated by Django 5.0 on 2024-11-21 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('task_app', '0019_job_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_view_job', "Can view Job's details"), ('can_view_jobs', 'Can view Jobs list'), ('can_create_job', 'Can create Job'), ('can_edit_job', 'Can edit Job'), ('can_pause_job', 'Can pause Job'), ('can_resume_job', 'Can resume Job'), ('can_delete_job', 'Can delete Job')]},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'permissions': [('can_view_task', "Can view Task's details"), ('can_view_tasks', 'Can view Tasks list'), ('can_create_task', 'Can create Task'), ('can_edit_task', 'Can edit Task'), ('can_restart_task', 'Can restart Task'), ('can_pause_task', 'Can pause Task'), ('can_resume_task', 'Can resume Task'), ('can_cancel_task', 'Can cancel Task'), ('can_delete_task', 'Can delete Task')]},
        ),
        migrations.AddField(
            model_name='timecondition',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
