# Generated by Django 5.0 on 2024-11-21 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0020_alter_job_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='periodic_task',
        ),
    ]
