# Generated by Django 5.0 on 2024-11-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0021_remove_job_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='stopped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STARTING', 'Starting'), ('PAUSED', 'Paused'), ('RUNNING', 'Running'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='STARTING', max_length=10),
        ),
    ]
