# Generated by Django 5.0 on 2024-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0022_task_stopped_at_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
