# Generated by Django 5.0 on 2024-12-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0023_alter_task_finished_at_alter_task_stopped_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sql_file',
        ),
    ]
