# Generated by Django 5.0 on 2025-02-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0024_remove_task_sql_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
