# Generated by Django 5.0 on 2025-02-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0025_limitcondition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LimitCondition',
            new_name='ThresholdCondition',
        ),
        migrations.RenameField(
            model_name='thresholdcondition',
            old_name='limit',
            new_name='threshold_value',
        ),
    ]
