# Generated by Django 5.0 on 2025-02-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0026_rename_limitcondition_thresholdcondition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecondition',
            name='crontab',
        ),
    ]
