

""" Constants for Continente Scraper """

""" Recipe Links"""

ROOT = "https://feed.continente.pt/receitas/"
CONTINENTE_SEARCH_VEGETARIAN_URL = f"{ROOT}vegetariano"
CONTINENTE_SEARCH_MEAT_URL = f"{ROOT}carne"
CONTINENTE_SEARCH_SOUP_URL = f"{ROOT}sopas"
CONTINENTE_SEARCH_SALAD_URL = f"{ROOT}saladas"
CONTINENTE_SEARCH_FISH_URL= f"{ROOT}peixe"
CONTINENTE_SEARCH_BREAKFAST_URL = f"{ROOT}pequeno-almoço" #Só serve para pequenos almoços

SEARCH_RECIPES = [CONTINENTE_SEARCH_VEGETARIAN_URL, CONTINENTE_SEARCH_MEAT_URL, CONTINENTE_SEARCH_SOUP_URL, CONTINENTE_SEARCH_SALAD_URL, CONTINENTE_SEARCH_FISH_URL, CONTINENTE_SEARCH_BREAKFAST_URL]