# Generated by Django 5.0 on 2024-07-17 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_company_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user_account',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_company', to=settings.AUTH_USER_MODEL),
        ),
    ]
