# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc python3-dev

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django application code
COPY . /app/

# Collect static files
RUN python manage.py collectstatic --noinput

# Install Playwright Dependencies and Browsers
RUN playwright install-deps
RUN playwright install


# Run Gunicorn
CMD gunicorn config.wsgi:application --bind 0.0.0.0:8000

