# Generated by Django 5.0 on 2025-06-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process'), ('TEST', 'Test'), ('FAILURE', 'Failure'), ('EMPTY', 'Empty'), ('MID_FAILURE', 'Mid Failure')], default=None, max_length=12, null=True)),
                ('process', models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=20, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Job Name')),
                ('log_path', models.CharField(max_length=255)),
                ('starting_condition_id', models.PositiveIntegerField(null=True)),
                ('stopping_condition_id', models.PositiveIntegerField(null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('can_view_job', "Can view Job's details"), ('can_view_jobs', 'Can view Jobs list'), ('can_create_job', 'Can create Job'), ('can_edit_job', 'Can edit Job'), ('can_force_start_job', 'Can force start Job'), ('can_enable_job', 'Can pause Job'), ('can_disable_job', 'Can resume Job'), ('can_delete_job', 'Can delete Job')],
            },
        ),
        migrations.CreateModel(
            name='JobTriggerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('STOPPING_CONDITION', 'Stopping Condition'), ('STARTING_CONDITION', 'Starting Condition'), ('FORCE_START', 'Force Start')], default=None, max_length=18, null=True)),
                ('action', models.CharField(choices=[('CREATED_TASK', 'Created New Task'), ('RESUMED_TASK', 'Resumed Task'), ('REST', 'Rest')], default=None, max_length=12, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process'), ('TEST', 'Test'), ('FAILURE', 'Failure'), ('EMPTY', 'Empty'), ('MID_FAILURE', 'Mid Failure')], default=None, max_length=12, null=True)),
                ('process', models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=20, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sql_path', models.CharField(blank=True, max_length=255, null=True)),
                ('debug_mode', models.BooleanField(default=False)),
                ('step', models.IntegerField(default=0)),
                ('links', models.IntegerField(blank=True, default=0, null=True)),
                ('items_processed', models.IntegerField(blank=True, default=0, null=True)),
                ('items_expected', models.IntegerField(blank=True, default=0, null=True)),
                ('warnings', models.IntegerField(blank=True, default=0, null=True)),
                ('errors', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PAUSED', 'Paused'), ('RUNNING', 'Running'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='WAITING', max_length=10)),
            ],
            options={
                'permissions': [('can_view_task', "Can view Task's details"), ('can_view_tasks', 'Can view Tasks list'), ('can_create_task', 'Can create Task'), ('can_edit_task', 'Can edit Task'), ('can_restart_task', 'Can restart Task'), ('can_pause_task', 'Can pause Task'), ('can_resume_task', 'Can resume Task'), ('can_cancel_task', 'Can cancel Task'), ('can_delete_task', 'Can delete Task')],
            },
        ),
        migrations.CreateModel(
            name='TaskStatusConditionAwaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThresholdCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
