# Generated by Django 5.0 on 2025-02-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('EMPTY', 'Empty'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('FAILURE', 'Failure')], default=None, max_length=12, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Job Name')),
                ('log_path', models.CharField(max_length=255)),
                ('starting_condition_id', models.PositiveIntegerField(null=True)),
                ('stopping_condition_id', models.PositiveIntegerField(null=True)),
                ('continue_mode', models.BooleanField(default=False)),
                ('debug_mode', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('can_view_job', "Can view Job's details"), ('can_view_jobs', 'Can view Jobs list'), ('can_create_job', 'Can create Job'), ('can_edit_job', 'Can edit Job'), ('can_pause_job', 'Can pause Job'), ('can_resume_job', 'Can resume Job'), ('can_delete_job', 'Can delete Job')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('EMPTY', 'Empty'), ('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('FAILURE', 'Failure')], default=None, max_length=12, null=True)),
                ('started_at', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('log_path', models.CharField(blank=True, max_length=255, null=True)),
                ('sql_file', models.CharField(blank=True, max_length=255, null=True)),
                ('extract_sql_file', models.CharField(blank=True, max_length=255, null=True)),
                ('transform_sql_file', models.CharField(blank=True, max_length=255, null=True)),
                ('debug_mode', models.BooleanField(default=False)),
                ('step', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('STARTING', 'Starting'), ('PAUSED', 'Paused'), ('RUNNING', 'Running'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='STARTING', max_length=10)),
            ],
            options={
                'permissions': [('can_view_task', "Can view Task's details"), ('can_view_tasks', 'Can view Tasks list'), ('can_create_task', 'Can create Task'), ('can_edit_task', 'Can edit Task'), ('can_restart_task', 'Can restart Task'), ('can_pause_task', 'Can pause Task'), ('can_resume_task', 'Can resume Task'), ('can_cancel_task', 'Can cancel Task'), ('can_delete_task', 'Can delete Task')],
            },
        ),
        migrations.CreateModel(
            name='ThresholdCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_value', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
