# Generated by Django 5.0 on 2025-06-15 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('etl_app', '0001_initial'),
        ('user_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='user_app.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='etl_app.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='starting_condition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_condition_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='job',
            name='stopping_condition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_condition_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='jobtriggerhistory',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_history', to='etl_app.job'),
        ),
        migrations.AddField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_app.company'),
        ),
        migrations.AddField(
            model_name='task',
            name='owner_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='etl_app.job'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='etl_app.job'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='etl_app.task'),
        ),
        migrations.AddField(
            model_name='job',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='etl_app.task'),
        ),
        migrations.AddField(
            model_name='taskstatusconditionawaiter',
            name='dependent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.task'),
        ),
        migrations.AddField(
            model_name='taskstatusconditionawaiter',
            name='owner_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks_awaiter', to='etl_app.task'),
        ),
        migrations.AddField(
            model_name='timecondition',
            name='periodic_task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
