# Generated by Django 5.0 on 2025-02-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='debug_mode',
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process'), ('TEST', 'Test'), ('FAILURE', 'Failure'), ('EMPTY', 'Empty')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process'), ('TEST', 'Test'), ('FAILURE', 'Failure'), ('EMPTY', 'Empty')], default=None, max_length=12, null=True),
        ),
    ]
