# Generated by Django 5.0 on 2024-06-19 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0002_task_max_records_task_new_copy_remove_task_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='users',
        ),
    ]
