# Generated by Django 5.0 on 2025-06-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='warnings',
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning')], max_length=7)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='etl_app.task')),
            ],
        ),
    ]
