# Generated by Django 5.0 on 2025-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0003_remove_task_errors_remove_task_warnings_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='stack_trace',
            field=models.TextField(blank=True, null=True),
        ),
    ]
