# Generated by Django 5.0 on 2025-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0003_remove_job_debug_mode_alter_job_type_alter_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='sub_type',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='sub_type',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=12, null=True),
        ),
    ]
