# Generated by Django 5.0 on 2024-06-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0003_rename_user_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_records',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
