# Generated by Django 5.0 on 2025-06-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0004_issue_stack_trace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=7),
        ),
    ]
