# Generated by Django 5.0 on 2025-02-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0004_job_sub_type_task_sub_type'),
        ('user_app', '0002_remove_company_email_alter_company_user_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients and Recipes')], default=None, max_length=20, null=True)),
                ('companys', models.ManyToManyField(related_name='processes', to='user_app.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
