# Generated by Django 5.0 on 2025-06-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0005_remove_issue_created_at_alter_issue_issue_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_type',
            new_name='type',
        ),
    ]
