# Generated by Django 5.0 on 2025-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0005_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sub_type',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='sub_type',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
