# Generated by Django 5.0 on 2024-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0005_remove_task_users_task_user_alter_task_new_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_records',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
