# Generated by Django 5.0 on 2025-02-28 16:04

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0006_alter_job_sub_type_alter_task_sub_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='sub_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sub_type',
        ),
        migrations.AddField(
            model_name='job',
            name='process',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='process',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=40),
        ),
    ]
