# Generated by Django 5.0 on 2025-02-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0007_remove_job_sub_type_remove_task_sub_type_job_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=20),
        ),
    ]
