# Generated by Django 5.0 on 2025-09-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0007_issue_created_at_issue_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='task',
        ),
        migrations.AddField(
            model_name='issue',
            name='task',
            field=models.ManyToManyField(related_name='issues', to='etl_app.task'),
        ),
    ]
