# Generated by Django 5.0 on 2024-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0008_alter_task_max_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='max_records',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
