# Generated by Django 5.0 on 2025-11-17 19:25

import apps.etl_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0008_remove_issue_task_issue_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='propreties',
            field=models.JSONField(blank=True, default=apps.etl_app.models.default_properties),
        ),
        migrations.AddField(
            model_name='task',
            name='propreties',
            field=models.JSONField(blank=True, default=apps.etl_app.models.default_properties),
        ),
    ]
