# Generated by Django 5.0 on 2025-02-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0008_alter_job_process_alter_task_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=20, null=True),
        ),
    ]
