# Generated by Django 5.0 on 2025-03-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0009_alter_job_process_alter_task_process'),
        ('user_app', '0005_rename_process_company_processes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='user_app.company'),
        ),
    ]
