# Generated by Django 5.0 on 2025-11-17 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0009_job_propreties_task_propreties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='propreties',
            new_name='properties',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='propreties',
            new_name='properties',
        ),
    ]
