# Generated by Django 5.0 on 2025-03-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0010_alter_task_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='errors',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='items',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='warnigs',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='process',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process'), ('TEST', 'Test'), ('FAILURE', 'Failure'), ('EMPTY', 'Empty'), ('MID_FAILURE', 'Mid Failure')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process'), ('TEST', 'Test'), ('FAILURE', 'Failure'), ('EMPTY', 'Empty'), ('MID_FAILURE', 'Mid Failure')], default=None, max_length=12, null=True),
        ),
    ]
