# Generated by Django 5.0 on 2024-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0010_task_log_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sql_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
