# Generated by Django 5.0 on 2024-06-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0011_task_sql_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='new_copy',
        ),
    ]
