# Generated by Django 5.0 on 2025-03-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0011_task_errors_task_items_task_warnigs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='errors',
            new_name='item_errors',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='warnigs',
            new_name='items_warnings',
        ),
        migrations.AddField(
            model_name='task',
            name='links',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='links_errors',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='links_warnings',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_errors',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='total_warnings',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
