# Generated by Django 5.0 on 2025-04-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0012_rename_errors_task_item_errors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
