# Generated by Django 5.0 on 2024-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0012_remove_task_new_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
