# Generated by Django 5.0 on 2024-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0013_task_celery_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='paused_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='resumed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('STARTING', 'Starting'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('CANCELED', 'Canceled'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='STARTING', max_length=10),
        ),
    ]
