# Generated by Django 5.0 on 2025-04-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0013_alter_task_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='extract_sql_file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='transform_sql_file',
        ),
    ]
