# Generated by Django 5.0 on 2025-04-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0014_remove_task_extract_sql_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sub_sql_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
