# Generated by Django 5.0 on 2025-04-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0015_task_sub_sql_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='items',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='items_warnings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='links',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='links_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='links_warnings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_errors',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_warnings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
