# Generated by Django 5.0 on 2025-04-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0016_alter_task_item_errors_alter_task_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='item_errors',
            new_name='items_errors',
        ),
    ]
