# Generated by Django 5.0 on 2024-07-11 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('etl_app', '0016_alter_task_parent_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_records', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('EXTRACT', 'Extract'), ('TRANSFORM', 'Transform'), ('LOAD', 'Load'), ('FULL_PROCESS', 'Full Process')], default=None, max_length=12, null=True)),
                ('name', models.CharField(max_length=255)),
                ('crontab', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='etl_app.job')),
                ('periodic_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
