# Generated by Django 5.0 on 2025-04-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0017_rename_item_errors_task_items_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
