# Generated by Django 5.0 on 2024-07-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0017_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='task',
        ),
        migrations.AddField(
            model_name='job',
            name='last_run',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='etl_app.job'),
        ),
    ]
