# Generated by Django 5.0 on 2025-04-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0018_task_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='items',
            new_name='items_expected',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='links',
            new_name='items_processed',
        ),
        migrations.AddField(
            model_name='task',
            name='links_expected',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='links_processed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
