# Generated by Django 5.0 on 2025-04-29 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0019_rename_items_task_items_expected_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='items_errors',
            new_name='errors',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='items_warnings',
            new_name='links',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='links_errors',
            new_name='warnings',
        ),
        migrations.RemoveField(
            model_name='task',
            name='links_expected',
        ),
        migrations.RemoveField(
            model_name='task',
            name='links_processed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='links_warnings',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_errors',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_warnings',
        ),
    ]
