# Generated by Django 5.0 on 2025-05-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0020_rename_items_errors_task_errors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwaitingTaskCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_status', models.CharField(max_length=10, verbose_name=[('STARTING', 'Starting'), ('PAUSED', 'Paused'), ('RUNNING', 'Running'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')])),
                ('triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl_app.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
