# Generated by Django 5.0 on 2025-05-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0021_awaitingtaskcondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_status', models.CharField(max_length=10, verbose_name='Task.Status.choices')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='awaitingtaskcondition',
            name='required_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='continue_mode',
        ),
    ]
