# Generated by Django 5.0 on 2024-07-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0021_alter_task_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
    ]
