# Generated by Django 5.0 on 2024-07-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0022_remove_job_parent_task_remove_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='etl_app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='etl_app.task'),
        ),
    ]
