# Generated by Django 5.0 on 2025-05-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0022_taskstatuscondition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatuscondition',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etl_app.task'),
            preserve_default=False,
        ),
    ]
