# Generated by Django 5.0 on 2025-05-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0023_taskstatuscondition_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_view_job', "Can view Job's details"), ('can_view_jobs', 'Can view Jobs list'), ('can_create_job', 'Can create Job'), ('can_edit_job', 'Can edit Job'), ('can_enable_job', 'Can pause Job'), ('can_disable_job', 'Can resume Job'), ('can_delete_job', 'Can delete Job')]},
        ),
    ]
