# Generated by Django 5.0 on 2024-07-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('etl_app', '0024_alter_job_crontab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='crontab',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule'),
        ),
    ]
