# Generated by Django 5.0 on 2025-05-08 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('etl_app', '0024_alter_job_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='starting_condition_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='starting_condition_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stopping_condition_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='stopping_condition_type',
        ),
        migrations.CreateModel(
            name='JobConditionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_id', models.PositiveIntegerField()),
                ('TYPE', models.CharField(choices=[('START', 'Start'), ('STOP', 'Stop')], default=None, max_length=12, null=True)),
                ('condition_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_links', to='etl_app.job')),
            ],
            options={
                'unique_together': {('job', 'condition_type', 'condition_id', 'TYPE')},
            },
        ),
    ]
