# Generated by Django 5.0 on 2024-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0025_alter_job_crontab'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extract_sql_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='transform_sql_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
