# Generated by Django 5.0 on 2025-05-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('etl_app', '0025_remove_job_starting_condition_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AwaitingTaskCondition',
            new_name='TaskStatusConditionAwaiter',
        ),
        migrations.RemoveField(
            model_name='taskstatuscondition',
            name='task',
        ),
        migrations.AddField(
            model_name='job',
            name='starting_condition_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='starting_condition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_condition_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='job',
            name='stopping_condition_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stopping_condition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_condition_type', to='contenttypes.contenttype'),
        ),
        migrations.DeleteModel(
            name='JobConditionLink',
        ),
        migrations.DeleteModel(
            name='TaskStatusCondition',
        ),
    ]
