# Generated by Django 5.0 on 2025-05-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0026_rename_awaitingtaskcondition_taskstatusconditionawaiter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTriggerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CREATED_TASK', 'Created New Task'), ('RESUMED_TASK', 'Resumed Task')], default=None, max_length=12, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_history', to='etl_app.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
