# Generated by Django 5.0 on 2025-05-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0027_jobtriggerhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
