# Generated by Django 5.0 on 2024-07-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0027_alter_job_user_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='company',
        ),
    ]
