# Generated by Django 5.0 on 2024-09-12 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('django_celery_beat', '0018_improve_crontab_helptext'),
        ('etl_app', '0028_rename_user_job_company_rename_user_task_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxRecordsCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_records', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='task',
            old_name='max_records',
            new_name='stopping_condition_max_records',
        ),
        migrations.RemoveField(
            model_name='job',
            name='crontab',
        ),
        migrations.RemoveField(
            model_name='job',
            name='max_records',
        ),
        migrations.RemoveField(
            model_name='job',
            name='periodic_task',
        ),
        migrations.AddField(
            model_name='job',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='log_path',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_jobs', to='etl_app.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='starting_condition_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='starting_condition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_condition_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='job',
            name='stopping_condition_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='stopping_condition_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stop_condition_type', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='task',
            name='debug_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Job Name'),
        ),
        migrations.AlterField(
            model_name='job',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='etl_app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='etl_app.job'),
        ),
        migrations.CreateModel(
            name='TimeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crontab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.crontabschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
