# Generated by Django 5.0 on 2025-05-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0028_alter_task_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryTask',
        ),
    ]
