# Generated by Django 5.0 on 2025-05-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0030_task_celery_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='stopped_at',
            new_name='paused_at',
        ),
        migrations.AddField(
            model_name='task',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
