# Generated by Django 5.0 on 2025-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0031_rename_stopped_at_task_paused_at_task_resumed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='sub_sql_file',
        ),
        migrations.AddField(
            model_name='jobtriggerhistory',
            name='action',
            field=models.CharField(choices=[('CREATED_TASK', 'Created New Task'), ('RESUMED_TASK', 'Resumed Task'), ('REST', 'Rest')], default=None, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='jobtriggerhistory',
            name='type',
            field=models.CharField(choices=[('STOPPING_CONDITION', 'Stopping Condition'), ('STARTING_CONDITION', 'Starting Condition'), ('FORCE_START', 'Force Start')], default=None, max_length=18, null=True),
        ),
    ]
