# Generated by Django 5.0 on 2025-05-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0032_remove_task_sub_sql_file_jobtriggerhistory_action_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'permissions': [('can_view_job', "Can view Job's details"), ('can_view_jobs', 'Can view Jobs list'), ('can_create_job', 'Can create Job'), ('can_edit_job', 'Can edit Job'), ('can_force_start_job', 'Can force start Job'), ('can_enable_job', 'Can pause Job'), ('can_disable_job', 'Can resume Job'), ('can_delete_job', 'Can delete Job')]},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='job',
            new_name='parent_job',
        ),
    ]
