# Generated by Django 5.0 on 2025-05-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0033_alter_job_options_rename_job_task_parent_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('PAUSED', 'Paused'), ('RUNNING', 'Running'), ('CANCELED', 'Canceled'), ('STOPPED', 'Stopped'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='WAITING', max_length=10),
        ),
    ]
