# Generated by Django 5.0 on 2025-05-16 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0034_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskstatusconditionawaiter',
            old_name='task',
            new_name='dependent_task',
        ),
        migrations.AddField(
            model_name='taskstatusconditionawaiter',
            name='owner_task',
            field=models.ForeignKey(default=98, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks_awaiter', to='etl_app.task'),
            preserve_default=False,
        ),
    ]
