# Generated by Django 5.0 on 2025-05-22 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0035_rename_task_taskstatusconditionawaiter_dependent_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_tasks', to='etl_app.job'),
        ),
    ]
