# Generated by Django 5.0 on 2025-05-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0036_task_owner_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='owner_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='etl_app.job'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='etl_app.job'),
        ),
    ]
