# Generated by Django 5.0 on 2025-05-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0037_alter_task_owner_job_alter_task_parent_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='sql_file',
            new_name='sql_path',
        ),
    ]
