# Generated by Django 5.0 on 2025-06-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('seen', models.BooleanField(default=False)),
                ('type', models.IntegerField(default=-1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
