# Generated by Django 3.2.6 on 2024-05-13 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('PEQUENO ALMOÇO', 'Pequeno almoço'), ('LANCHE DA MANHÃ', 'Lanche da manhã'), ('ALMOÇO', 'Almoço'), ('LANCHE DA TARDE', 'Lanche da tarde'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia')], max_length=255)),
                ('portion', models.IntegerField(null=True)),
                ('realization_date', models.DateTimeField()),
                ('checked_done', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='recipe_app.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
