# Generated by Django 5.0 on 2024-07-20 15:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calendarentry',
            name='tag',
            field=models.CharField(choices=[('PEQUENO ALMOÇO', 'Pequeno almoço'), ('LANCHE DA MANHÃ', 'Lanche da manhã'), ('ALMOÇO', 'Almoço'), ('LANCHE DA TARDE', 'Lanche da tarde'), ('JANTAR', 'Jantar'), ('CEIA', 'Ceia'), ('OTHER', 'Other')], default='OTHER', max_length=15),
        ),
    ]
