# Generated by Django 5.0 on 2025-06-15 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendar_app', '0001_initial'),
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarentry',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_entries', to='recipe_app.recipe'),
        ),
    ]
