


TESTING_ACCOUNT_A = "TestingAccountA"
TESTING_ACCOUNT_B = "TestingAccountB"
TESTING_ACCOUNT_C = "TestingAccountC"
TESTING_ACCOUNT_A_PASSWORD = "PasswordA123!"
TESTING_ACCOUNT_B_PASSWORD = "PasswordB123!"
TESTING_ACCOUNT_C_PASSWORD = "PasswordC123!"