# Generated by Django 5.0 on 2025-06-15 23:00

import django.db.models.deletion
import multiselectfield.db.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=40)),
                ('username', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, default='avatar7.png', max_length=255)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('birth_date', models.DateTimeField(null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('user_portion', models.IntegerField(default=-1)),
                ('is_active', models.BooleanField(default=True)),
                ('fmc_token', models.CharField(blank=True, default='', max_length=255)),
                ('height', models.FloatField(default=-1)),
                ('weight', models.FloatField(default=-1)),
                ('is_admin', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('follows_c', models.IntegerField(default=0)),
                ('followers_c', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_level', models.CharField(choices=[('1', 'Nothing'), ('1.2', 'Sedentary'), ('1.375', 'Light'), ('1.465', 'Moderate'), ('1.55', 'Active'), ('1.725', 'Very Active'), ('1.9', 'Extra Active')], default='1', max_length=5)),
                ('profile_type', models.CharField(choices=[('PROTECT', 'Protect'), ('PRIVATE', 'Private'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=10)),
                ('type', models.CharField(choices=[('Placeholder', 'Placeholder'), ('Company', 'Company'), ('Normal', 'Normal'), ('Application Staff', 'Application Staff'), ('Application Admin', 'Application Admin'), ('Company Staff', 'Company Staff'), ('Company Admin', 'Company Admin')], default='Normal')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=1, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('security_group', models.ManyToManyField(blank=True, related_name='users', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', to='auth.permission')),
            ],
            options={
                'permissions': [('can_view_user', "Can view User's details"), ('can_view_users', 'Can view Users list'), ('can_invite_user', 'Can invite a User'), ('can_edit_user', 'Can edit a User'), ('can_delete_user', 'Can delete a User'), ('can_enable_user', 'Can Enable a User'), ('can_disable_user', 'Can Disable a User')],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('imgs_bucket', models.CharField(max_length=255)),
                ('processes', multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=40)),
                ('user_account', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_company', "Can view Company's details"), ('can_view_companies', 'Can view Companies list'), ('can_create_company', 'Can resend a Company'), ('can_edit_company', 'Can edit a Company'), ('can_delete_company', 'Can delete a Company')],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user_app.company'),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeds', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followeds_request', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.FloatField()),
                ('calories', models.FloatField()),
                ('fat_upper_limit', models.FloatField()),
                ('fat_lower_limit', models.FloatField()),
                ('saturated_fat', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('proteins_upper_limit', models.FloatField()),
                ('proteins_lower_limit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user_app.company')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_view_invite', "Can view Invite's details"), ('can_view_invites', 'Can view Invites list'), ('can_resend_invite', 'Can resend a Invite'), ('can_edit_invite', 'Can edit a Invite'), ('can_delete_invite', 'Can delete a Invite')],
            },
        ),
    ]
