# Generated by Django 5.0 on 2025-06-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='avatar6.png', max_length=255),
        ),
    ]
