# Generated by Django 5.0 on 2025-02-21 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
        migrations.AlterField(
            model_name='company',
            name='user_account',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Company', 'Company'), ('Normal', 'Normal'), ('Staff', 'Staff'), ('SuperUser', 'Super User')], default='Normal'),
        ),
    ]
