# Generated by Django 5.0 on 2025-02-28 15:55

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_company_email_alter_company_user_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activity_level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=1, max_length=40),
            preserve_default=False,
        ),
    ]
