# Generated by Django 5.0 on 2025-02-28 15:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_company_activity_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='activity_level',
        ),
        migrations.AddField(
            model_name='company',
            name='process',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes'), ('INGREDIENTS_RECIPES', 'Ingredients & Recipes')], default=None, max_length=40),
        ),
    ]
