# Generated by Django 5.0 on 2025-02-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_remove_company_activity_level_company_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='process',
            new_name='processes',
        ),
    ]
