# Generated by Django 5.0 on 2025-03-21 18:30

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_rename_process_company_processes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='processes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=None, max_length=40),
        ),
    ]
