# Generated by Django 5.0 on 2024-07-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('N', 'Normal'), ('C', 'Company'), ('P', 'Premium'), ('A', 'Admin')], default='N', max_length=1),
        ),
    ]
