# Generated by Django 5.0 on 2025-05-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0006_alter_company_processes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Placeholder', 'Placeholder'), ('Company', 'Company'), ('Normal', 'Normal'), ('Application Staff', 'Application Staff'), ('Application Admin', 'Application Admin'), ('Company Staff', 'Company Staff'), ('Company Admin', 'Company Admin')], default='Normal'),
        ),
    ]
