# Generated by Django 5.0 on 2025-05-28 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_invitation_group_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='user_app.company'),
            preserve_default=False,
        ),
    ]
