# Generated by Django 5.0 on 2025-08-18 16:24

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='processes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('INGREDIENTS', 'Ingredients'), ('RECIPES', 'Recipes')], default=list, max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='avatar6.png', max_length=255),
        ),
    ]
