# Generated by Django 5.0 on 2025-05-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_invitation_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='invited_by',
            new_name='inviter',
        ),
    ]
