# Generated by Django 5.0 on 2025-05-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_rename_invited_by_invitation_inviter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'permissions': [('can_view_invite', "Can view Invite's details"), ('can_view_invites', 'Can view Invites list'), ('can_edit_invite', 'Can edit a Invite'), ('can_delete_invite', 'Can delete a Invite')]},
        ),
    ]
