# Generated by Django 5.0 on 2025-05-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_invitation_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='email',
            new_name='invited',
        ),
    ]
