# Generated by Django 5.0 on 2025-05-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_alter_invitation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'permissions': [('can_view_company', "Can view Company's details"), ('can_view_companies', 'Can view Companies list'), ('can_create_company', 'Can resend a Company'), ('can_edit_company', 'Can edit a Company'), ('can_delete_company', 'Can delete a Company')]},
        ),
    ]
