# Generated by Django 5.0 on 2025-05-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_user_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_view_user', "Can view User's details"), ('can_view_users', 'Can view Users list'), ('can_invite_user', 'Can invite a User'), ('can_edit_user', 'Can edit a User'), ('can_delete_user', 'Can delete a User'), ('can_enable_user', 'Can Enable a User'), ('can_disable_user', 'Can Disable a User')]},
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateTimeField(null=True),
        ),
    ]
