# Generated by Django 5.0 on 2025-09-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0015_alter_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='group',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='avatar3.png', max_length=255),
        ),
    ]
