# Generated by Django 5.0 on 2025-09-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_remove_invitation_group_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='avatar2.png', max_length=255),
        ),
    ]
