# Generated by Django 5.0 on 2025-06-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0016_user_security_group_alter_user_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img_source',
            new_name='image',
        ),
    ]
