# Generated by Django 5.0 on 2025-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0021_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='avatar2.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('Placeholder', 'Placeholder'), ('Company', 'Company'), ('Normal', 'Normal'), ('Premium', 'Premium'), ('Application Staff', 'Application Staff'), ('Application Admin', 'Application Admin'), ('Company Staff', 'Company Staff'), ('Company Admin', 'Company Admin')], default='Normal'),
        ),
    ]
