# Generated by Django 5.0 on 2025-10-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0022_alter_user_image_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(blank=True, default='avatar4.png', max_length=255),
        ),
    ]
