# Generated by Django 5.0 on 2025-06-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_original', models.CharField(max_length=255)),
                ('quantity_normalized', models.FloatField(null=True)),
                ('units_normalized', models.CharField(max_length=255, null=True)),
                ('extra_quantity', models.FloatField(null=True)),
                ('extra_units', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NutritionInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('energy_kcal', models.FloatField(max_length=255)),
                ('energy_perc', models.FloatField(max_length=255)),
                ('fat_g', models.FloatField(max_length=255)),
                ('fat_perc', models.FloatField(max_length=255)),
                ('saturates_g', models.FloatField(max_length=255)),
                ('saturates_perc', models.FloatField(max_length=255)),
                ('carbohydrates_g', models.FloatField(max_length=255)),
                ('carbohydrates_perc', models.FloatField(max_length=255)),
                ('sugars_g', models.FloatField(max_length=255)),
                ('sugars_perc', models.FloatField(max_length=255)),
                ('fiber_g', models.FloatField(max_length=255)),
                ('protein_g', models.FloatField(max_length=255)),
                ('protein_perc', models.FloatField(max_length=255)),
                ('salt_g', models.FloatField(max_length=255)),
                ('salt_perc', models.FloatField(max_length=255)),
            ],
            options={
                'db_table': 'nutrition_information',
            },
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=255, null=True)),
                ('step', models.CharField(max_length=2)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255, null=True)),
                ('video', models.CharField(max_length=255, null=True)),
                ('difficulty', models.CharField(max_length=255, null=True)),
                ('portion_lower', models.CharField(max_length=255, null=True)),
                ('portion_upper', models.CharField(max_length=255, null=True)),
                ('portion_units', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=255, null=True)),
                ('time_units', models.CharField(null=True)),
                ('views', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('source_rating', models.FloatField(null=True)),
                ('source_link', models.CharField(max_length=255, null=True, unique=True)),
                ('verified', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-views'],
                'permissions': [('can_view_recipe', "Can view Recipe's details"), ('can_view_recipes', 'Can view Recipes list'), ('can_delete_recipe', 'Can delete Recipe')],
            },
        ),
        migrations.CreateModel(
            name='RecipeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], max_length=20)),
            ],
            options={
                'permissions': [('can_view_audit_log', "Can view Audit Log's details"), ('can_view_audit_logs', 'Can view Audit Logs list'), ('can_delete_audit_log', 'Can delete Audit Log'), ('can_accept_audit_log', 'Can accept Audit Log'), ('can_unaccept_audit_log', 'Can unaccept Audit Log'), ('can_review_audit_log', 'Can review Audit Log'), ('can_unreview_audit_log', 'Can unreview Audit Log')],
            },
        ),
        migrations.CreateModel(
            name='RecipeAuditLogStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('UNNACCEPTED', 'Unaccepted'), ('REVIEWED', 'Reviewed'), ('UNREVIEWED', 'Unreviewed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('NutritionInformation', 'Nutrition Information'), ('Ingredient', 'Ingredient'), ('Preparation', 'Preparation'), ('Detail', 'Detail'), ('Other', 'Other')], default='Other', max_length=20, null=True)),
                ('status', models.CharField(choices=[('RESOLVED', 'Resolved'), ('SEEN', 'Seen'), ('ON_HOLD', 'On Hold'), ('PENDING', 'Pending')], default='PENDING', max_length=10, null=True)),
            ],
            options={
                'permissions': [('can_view_recipe_report', "Can view Recipe Report's details"), ('can_view_recipe_reports', 'Can view Recipe Reports list'), ('can_create_recipe_report', 'Can create Recipe Report'), ('can_delete_recipe_report', 'Can delete Recipe Report')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsefulTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
