# Generated by Django 5.0 on 2025-04-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='img_source',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='portion',
            new_name='portion_lower',
        ),
        migrations.AddField(
            model_name='recipe',
            name='portion_units',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='portion_upper',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time_units',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
