# Generated by Django 5.0 on 2025-07-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='video',
            new_name='video_link',
        ),
    ]
