# Generated by Django 5.0 on 2025-04-30 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_rename_img_source_recipe_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='useful_tools', to='recipe_app.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
