# Generated by Django 4.2.9 on 2024-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_comment_created_at_comment_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereport',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('SEEN', 'Seen'), ('PENDING', 'Pending')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
