# Generated by Django 5.0 on 2025-08-22 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_rename_video_recipe_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefultool',
            old_name='text',
            new_name='name',
        ),
    ]
