# Generated by Django 5.0 on 2025-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_usefultool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usefultool',
            name='recipe',
        ),
        migrations.AddField(
            model_name='usefultool',
            name='recipe',
            field=models.ManyToManyField(related_name='useful_tools', to='recipe_app.recipe'),
        ),
    ]
