# Generated by Django 5.0 on 2025-04-30 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_remove_usefultool_recipe_usefultool_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeauditlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipeauditlog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='recipeauditlog',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='recipeauditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='recipeauditlog',
            name='field',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recipeauditlog',
            name='recipe',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='recipe_app.recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeauditlog',
            name='text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
