# Generated by Django 4.2.9 on 2024-06-01 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_recipereport_status_alter_ingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='users_likes',
            new_name='likes',
        ),
    ]
