# Generated by Django 5.0 on 2025-08-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_rename_text_usefultool_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefultool',
            old_name='name',
            new_name='text',
        ),
    ]
