# Generated by Django 5.0 on 2025-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_rename_name_usefultool_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeauditlog',
            name='update_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('None', 'None')], default='None', max_length=20),
        ),
    ]
