# Generated by Django 5.0 on 2025-04-30 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_app', '0020_rename_items_errors_task_errors_and_more'),
        ('recipe_app', '0005_rename_timestamp_recipeauditlog_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeauditlog',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_audit_logs', to='etl_app.task'),
            preserve_default=False,
        ),
    ]
