# Generated by Django 5.0 on 2025-04-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_recipeauditlog_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usefultool',
            old_name='recipe',
            new_name='recipes',
        ),
    ]
