# Generated by Django 5.0 on 2025-09-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0006_recipeauditlog_update_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeauditlog',
            old_name='update_type',
            new_name='sub_type',
        ),
    ]
