# Generated by Django 5.0 on 2025-04-30 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_rename_recipe_usefultool_recipes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeauditlog',
            old_name='text',
            new_name='description',
        ),
    ]
