# Generated by Django 4.2.9 on 2024-06-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_remove_comment_likes_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked_clients',
            field=models.ManyToManyField(related_name='likes', to='recipe_app.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='saved_clients',
            field=models.ManyToManyField(related_name='saves', to='recipe_app.recipe'),
        ),
    ]
