# Generated by Django 5.0 on 2025-09-16 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_rename_update_type_recipeauditlog_sub_type'),
        ('user_app', '0019_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='user_app.company'),
        ),
    ]
