# Generated by Django 5.0 on 2025-04-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_rename_text_recipeauditlog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='units_normalized',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
