# Generated by Django 5.0 on 2025-09-17 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_recipe_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipereport',
            options={'permissions': [('can_view_recipe_report', "Can view Recipe Report's details"), ('can_view_recipe_reports', 'Can view Recipe Reports list'), ('can_create_recipe_report', 'Can create Recipe Report'), ('can_delete_recipe_report', 'Can delete Recipe Report'), ('can_review_recipe_report', 'Can review Recipe Report'), ('can_unreview_recipe_report', 'Can unreview Recipe Report')]},
        ),
        migrations.RenameField(
            model_name='recipereport',
            old_name='assigne',
            new_name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
