# Generated by Django 4.2.9 on 2024-06-01 22:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe_app', '0008_remove_recipe_likes_recipe_liked_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='liked_clients',
            field=models.ManyToManyField(related_name='liked_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='saved_clients',
            field=models.ManyToManyField(related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
