# Generated by Django 5.0 on 2025-04-30 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0009_alter_ingredientquantity_units_normalized'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-views'], 'permissions': [('can_view_recipe', "Can view Recipe's details"), ('can_view_recipes', 'Can view Recipes list'), ('can_edit_recipe', 'Can edit Recipe'), ('can_delete_recipe', 'Can delete Recipe'), ('can_verify_recipe', 'Can verify Recipe')]},
        ),
    ]
