# Generated by Django 5.0 on 2025-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0010_alter_recipereport_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='portion_lower',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='portion_upper',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
