# Generated by Django 5.0 on 2025-10-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_alter_recipe_portion_lower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time_units',
        ),
    ]
