# Generated by Django 5.0 on 2025-05-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_recipeauditlog_accepted_recipeauditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeauditlog',
            name='type',
            field=models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete')], default='Create', max_length=20),
            preserve_default=False,
        ),
    ]
