# Generated by Django 5.0 on 2024-07-03 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0011_alter_recipe_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='energia',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='energia_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='fibra',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='fibra_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='gordura',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='gordura_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='gordura_saturada',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='gordura_saturada_perc',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='hidratos_carbonos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='hidratos_carbonos_acucares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='proteina',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Preparation',
        ),
    ]
