# Generated by Django 5.0 on 2025-10-17 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_remove_recipe_time_units'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciperating',
            options={'permissions': [('can_view_recipes_rated', 'Can view Recipes Rated list'), ('can_create_recipe_rating', 'Can create Recipe Rating'), ('can_delete_recipe_rating', 'Can delete Recipe Rating')]},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rating',
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciperating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reciperating',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_recipe_user_rating'),
        ),
    ]
