# Generated by Django 5.0 on 2025-05-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_recipeauditlog_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-views'], 'permissions': [('can_view_recipe', "Can view Recipe's details"), ('can_view_recipes', 'Can view Recipes list'), ('can_edit_recipe', 'Can edit Recipe'), ('can_delete_recipe', 'Can delete Recipe')]},
        ),
        migrations.AlterModelOptions(
            name='recipeauditlog',
            options={'permissions': [('can_view_audit_log', "Can view Audit Log's details"), ('can_view_audit_logs', 'Can view Audit Logs list'), ('can_delete_audit_log', 'Can delete Audit Log'), ('can_accept_audit_log', 'Can accept Audit Log')]},
        ),
    ]
