# Generated by Django 5.0 on 2024-07-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_recipe_preparation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='preparation',
        ),
        migrations.CreateModel(
            name='Preparation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation', to='recipe_app.recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
