# Generated by Django 5.0 on 2025-05-02 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_alter_recipe_options_alter_recipeauditlog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-views'], 'permissions': [('can_view_recipe', "Can view Recipe's details"), ('can_view_recipes', 'Can view Recipes list'), ('can_delete_recipe', 'Can delete Recipe')]},
        ),
    ]
