# Generated by Django 5.0 on 2025-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_alter_reciperating_options_remove_recipe_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time_units',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
