# Generated by Django 5.0 on 2025-05-02 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0014_alter_recipe_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeauditlog',
            options={'permissions': [('can_view_audit_log', "Can view Audit Log's details"), ('can_view_audit_logs', 'Can view Audit Logs list'), ('can_delete_audit_log', 'Can delete Audit Log'), ('can_accept_audit_log', 'Can accept Audit Log'), ('can_refuse_audit_log', 'Can refuse Audit Log'), ('can_reviewed_audit_log', 'Can review Audit Log'), ('can_unreviewed_audit_log', 'Can unreview Audit Log')]},
        ),
        migrations.RemoveField(
            model_name='recipeauditlog',
            name='user',
        ),
        migrations.AddField(
            model_name='recipeauditlog',
            name='accepted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_accepted_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipeauditlog',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeauditlog',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reviewed_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
