# Generated by Django 5.0 on 2024-07-10 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0014_rename_recipes_preparation_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='preparation',
            name='step',
            field=models.CharField(max_length=2),
        ),
    ]
