# Generated by Django 5.0 on 2025-05-04 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0015_alter_recipeauditlog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeauditlog',
            options={'permissions': [('can_view_audit_log', "Can view Audit Log's details"), ('can_view_audit_logs', 'Can view Audit Logs list'), ('can_delete_audit_log', 'Can delete Audit Log'), ('can_accept_audit_log', 'Can accept Audit Log'), ('can_unaccept_audit_log', 'Can unaccept Audit Log'), ('can_review_audit_log', 'Can review Audit Log'), ('can_unreview_audit_log', 'Can unreview Audit Log')]},
        ),
        migrations.RemoveField(
            model_name='recipeauditlog',
            name='accepted_by',
        ),
        migrations.AlterField(
            model_name='recipeauditlog',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecipeAuditLogStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('UNNACCEPTED', 'Unaccepted'), ('REVIEWED', 'Reviewed'), ('UNREVIEWED', 'Unreviewed')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='recipe_app.recipeauditlog')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RecipeBackground',
        ),
    ]
