# Generated by Django 5.0 on 2025-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0016_alter_recipeauditlog_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='title',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='energia',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='energia_perc',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='fibra',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='fibra_perc',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='gordura',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='gordura_perc',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='gordura_saturada',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='gordura_saturada_perc',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='hidratos_carbonos',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='hidratos_carbonos_acucares',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='hidratos_carbonos_acucares_perc',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='hidratos_carbonos_perc',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='proteina',
        ),
        migrations.RemoveField(
            model_name='nutritioninformation',
            name='proteina_perc',
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='carbohydrates_g',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='carbohydrates_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='energy_kcal',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='energy_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='fat_g',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='fat_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='fiber_g',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='protein_g',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='protein_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='salt_g',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='salt_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='saturates_g',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='saturates_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='sugars_g',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nutritioninformation',
            name='sugars_perc',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='nutritioninformation',
            table='nutrition_information',
        ),
    ]
