# Generated by Django 5.0 on 2024-07-17 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0017_alter_recipe_source_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='users_liked',
            field=models.ManyToManyField(null=True, related_name='liked_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='users_saved',
            field=models.ManyToManyField(null=True, related_name='saved_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
