# Generated by Django 5.0 on 2025-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0017_rename_title_tag_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutritioninformation',
            name='carbohydrates_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='carbohydrates_perc',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='energy_kcal',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='energy_perc',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='fat_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='fat_perc',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='fiber_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='protein_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='protein_perc',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='salt_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='salt_perc',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='saturates_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='saturates_perc',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='sugars_g',
            field=models.FloatField(max_length=255),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='sugars_perc',
            field=models.FloatField(max_length=255),
        ),
    ]
