# Generated by Django 5.0 on 2025-05-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0018_alter_nutritioninformation_carbohydrates_g_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preparation',
            name='section',
            field=models.CharField(default='a', max_length=255),
            preserve_default=False,
        ),
    ]
