# Generated by Django 5.0 on 2024-07-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0019_alter_recipe_users_liked_alter_recipe_users_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='nutrition_information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe_app.nutritioninformation'),
        ),
    ]
