# Generated by Django 5.0 on 2025-05-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0019_preparation_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preparation',
            name='section',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
