# Generated by Django 5.0 on 2025-05-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0020_alter_preparation_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
