# Generated by Django 5.0 on 2025-05-04 21:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0021_alter_tag_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeauditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
