# Generated by Django 5.0 on 2024-07-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0021_recipeauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereport',
            name='type',
            field=models.CharField(choices=[('NutritionInformation', 'Nutrition Information'), ('Ingredient', 'Ingredient'), ('Preparation', 'Preparation'), ('Detail', 'Detail'), ('Other', 'Other')], default='Other', max_length=20, null=True),
        ),
    ]
