# Generated by Django 5.0 on 2024-07-18 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0022_recipereport_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipereport',
            name='assigne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipereport',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'Resolved'), ('SEEN', 'Seen'), ('ON_HOLD', 'On Hold'), ('PENDING', 'Pending')], default='PENDING', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipereport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_recipe_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
