# Generated by Django 5.0 on 2025-05-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0022_recipeauditlog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeauditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
