# Generated by Django 5.0 on 2025-05-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0023_alter_recipeauditlog_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipereport',
            options={'permissions': [('can_view_recipe_report', "Can view Recipe Report's details"), ('can_view_recipe_reports', 'Can view Recipe Reports list'), ('can_create_recipe_report', 'Can create Recipe Report'), ('can_delete_recipe_report', 'Can delete Recipe Report')]},
        ),
    ]
