# Generated by Django 5.0 on 2025-06-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0024_alter_recipereport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
